### ISSUE TITLE
kernel names question

### ISSUE THREAD

**Issue by jinz2014** [marcpaterno/gpuintegration#3]
Could you please point out the names of the following two kernels in the paper in the repository ?

Pagani-kernel  (Section 3.1)
mcubes-kernel  (Section 3.2)

**Comment by marcpaterno** [comment]
Hi Ioannis,

I'm not sure whether you receive notifications of issues submitted to the gpuintegration repository. If not, and you are willing to, I'll figure out how to get that arranged.

In any case, can you answer the qudestion "jinz2014" left?

thanks
Marc

________________________________________
From: jinz2014 ***@***.***>
Sent: Thursday, September 28, 2023 8:30 PM
To: marcpaterno/gpuintegration
Cc: Subscribed
Subject: [marcpaterno/gpuintegration] kernel names question (Issue #3)

Could you please point out the names of the following two kernels in the paper in the repository ?

Pagani-kernel (Section 3.1)
mcubes-kernel (Section 3.2)

**Comment by isaki001** [comment]
Hello,

The PAGANI kernel is under cuda/pagani/quad/GPUquad, and it's name is actually ```INTEGRATE_GPU_PHASE1```.
For m-Cubes, it is under cuda/mcubes/vegasT.cuh, and the name is ```vegas_kernel```

**Comment by f1974939505** [comment]
@isaki001 Hi ! I'm interested in running your code, PAGANI, but I'm having some trouble with the compilation process. Could you please provide some guidance on how to compile and use the code effectively?
I have configured cuda 12.6 and visual studio to be able to cmake the whole project, but I'm not quite sure how to use it further.
btw my GPU is 4090.

**Comment by marcpaterno** [comment]
I'm closing this issue because (1) the questions about the kernel names are answered and (2) the question about building on Windows is a distinct issue, #4.
