### ISSUE TITLE
How to use pagani

### ISSUE THREAD

**Issue by f1974939505** [marcpaterno/gpuintegration#4]
Hi ! I'm interested in running your code, but I'm having some trouble with the compilation process. Could you please provide some guidance on how to compile and use the code effectively? 
I have configured cuda 12.6 and visual studio to be able to cmake the whole project, but I'm not quite sure how to use it further.

**Comment by f1974939505** [comment]
btw my gpu is 4090

**Comment by marcpaterno** [comment]
Hello, Burnalysis. The code is this repository is built using CMake. However, I have never attempted to build it on Windows, and do not have any familiarity with the use of CMake on Windows. In addition, to build all of the targets in the project requires a large collection of tools. CMake on Unix systems allows the user a fine-grained choice of what to build, so that, for example, if one does not want to build the Kokkos version of the algorithms, there is no need to have an already-installed Kokkos version. I do not know how to handle that kind of things when using CMake on Windows.

**Comment by f1974939505** [comment]
@marcpaterno I have ubuntu system. How should I compile the code on Ubuntu?

**Comment by isaki001** [comment]
Hi @f1974939505, things should be much easier on Ubuntu and I would be happy to help.

We have some instructions at `https://github.com/marcpaterno/gpuintegration/wiki/Latest-Build-Instructions` that would be of some help. 

Could you try the CUDA example in the instructions first to see if any issues come up? If there are any errors we could take it from there. There is an example CMake command that should help and you would not need the flags for Kokkos, SYCL, oneAPI, CUDA_BACKEND. 

Make sure to set `GPUINTEGRATION_BUILD_CUDA` to true, to set the `TARGET_ARCH` for your machine, and to set `TOP_DIR` to the path of the `gpuintegration` directory.

**Comment by isaki001** [comment]
@f1974939505 I believe the instructions assume some familiarity with CMake. Let me know if that's not the case for you. I could provide more detail if needed.

**Comment by f1974939505** [comment]
@isaki001 That's kind. I've run the following 
`cmake .. -DGPUINTEGRATION_BUILD_CUDA=TRUE -DTARGET_ARCH=70-real`
and it returns a lot of errors like
"Target "interpolator_mem_usage" requires the language dialect "CUDA17" .
  But the current compiler "NVIDIA" does not support this, or CMake does not
  know the flags to enable it."
My cuda version is 12.6 and I have tried to reinstall cuda and it still such errors.

**Comment by f1974939505** [comment]
@isaki001 That's kind. I'm really not familiar with cmake.
I'm running the following code
`~/code/gpuintegration-master/build$ cmake .. -DGPUINTEGRATION_BUILD_CUDA=TRUE -DTARGET_ARCH=70-real`
and it returns errors:

CMake Error at /opt/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:756 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

ptxas fatal : Value 'sm_30' is not defined for option 'gpu-name'

  # --error 0xff --

That is part of returned errors. I'm not quite sure what the problem is.

**Comment by isaki001** [comment]
Hi @f1974939505 
There a few things that need to be tweaked. 

* The 70-real was for older architectures and will not work for your RTX 4090. I believe the right flag is 89-real, but I am not positive. A relatively quick search will give the right flag if this one doesn't work.
* You need to also pass this flag -DTOP_DIR="your_path/gpuintegration"

So, once you are at your build directory do:
`cmake -DGPUINTEGRATION_BUILD_CUDA=TRUE -DTARGET_ARCH=89-real -DTOP_DIR="your_path/gpuintegration" .. `

Can you give that a try and let me know if it fixes things?

**Comment by f1974939505** [comment]
The following is the current full input and error output.

gpuintegration-master/build$ cmake -DGPUINTEGRATION_BUILD_CUDA=TRUE -DTARGET_ARCH=89-real -DTOP_DIR="~/code/gpuintegration-master" ..
-- The CXX compiler identification is GNU 9.4.0
CMake Error at /opt/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:756 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp -v



  The output was:

  255

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ _HERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _THERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_SIZE_=64

  #$ NVVMIR_LIBRARY_DIR=/usr/lib/nvidia-cuda-toolkit/libdevice

  #$
  PATH=/usr/lib/nvidia-cuda-toolkit/bin:/usr/local/cuda-12.6/bin:/opt/cmake/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/24.7/compilers/bin:/home/junru/miniconda3/bin:/home/junru/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program
  Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/bin:/mnt/c/Program
  Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/libnvvp:/mnt/c/Program
  Files/Microsoft
  MPI/Bin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/e/ProgramData/Anaconda3/condabin:/mnt/e/ProgramData/mingw64/bin:/mnt/e/ProgramData/Anaconda3:/mnt/e/ProgramData/Anaconda3/Scripts:/mnt/d/texlive/2020:/mnt/d/texlive/2020/bin/win32:/mnt/e/ProgramData/Julia/bin:/mnt/e/ProgramData/chromedriver:/mnt/c/Program
  Files/dotnet:/mnt/e/ProgramData/Git/cmd:/mnt/c/Program Files/Wolfram
  Research/WolframScript:/mnt/c/Program Files (x86)/NVIDIA
  Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA
  NvDLISR:/mnt/c/Program Files/MATLAB/R2024a/bin:/mnt/c/Program Files
  (x86)/Windows Kits/10/Windows Performance Toolkit:/mnt/c/Program
  Files/Microsoft Visual
  Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64:/mnt/c/Program
  Files/NVIDIA Corporation/Nsight Compute
  2024.3.2:/mnt/c/Users/Burni/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Burni/AppData/Local/Programs/Microsoft
  VS Code/bin:/mnt/c/Users/Burni/.dotnet/tools:/snap/bin

  #$ LIBRARIES= -L/usr/lib/x86_64-linux-gnu/stubs -L/usr/lib/x86_64-linux-gnu

  #$ rm tmp/a_dlink.reg.c

  #$ gcc -D__CUDA_ARCH__=300 -E -x c++ -DCUDA_DOUBLE_MATH_FUNCTIONS
  -D__CUDACC__ -D__NVCC__ -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=1
  -D__CUDACC_VER_BUILD__=243 -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp1.ii"

  #$ cicc --c++14 --gnu_version=90400 --allow_managed -arch compute_30 -m64
  -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name
  "CMakeCUDACompilerId.fatbin.c" -tused -nvvmir-library
  "/usr/lib/nvidia-cuda-toolkit/libdevice/libdevice.10.bc"
  --gen_module_id_file --module_id_file_name
  "tmp/CMakeCUDACompilerId.module_id" --orig_src_file_name
  "CMakeCUDACompilerId.cu" --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.gpu" "tmp/CMakeCUDACompilerId.cpp1.ii" -o
  "tmp/CMakeCUDACompilerId.ptx"

  #$ ptxas -arch=sm_30 -m64 "tmp/CMakeCUDACompilerId.ptx" -o
  "tmp/CMakeCUDACompilerId.sm_30.cubin"

  ptxas fatal : Value 'sm_30' is not defined for option 'gpu-name'

  # --error 0xff --





Call Stack (most recent call first):
  /opt/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  /opt/cmake/share/cmake-3.27/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by f1974939505** [comment]
I doubt the problem is with the compiler. I noticed above that I was prompted that I had not set a compiler, but after I set gcc and g++ as compilers, only the prompt that I had not set a compiler disappeared, and the other errors were still there.

**Comment by isaki001** [comment]
It seems like it is not recognizing the architecture flag. 
The `sm_30` that pops up in the errors is definitely not right and it ends up being passed to the cuda compiler as a target architecture. 
I'm not sure if anything else is wrong as well, but I think finding out the right arch flag should be the first step. 

In your current environment, can you compile a simple hello world cuda program without cmake?

**Comment by f1974939505** [comment]
It works as follows.
$ nvcc 1.cu -o hello
$ ./hello
Hello World from GPU!

**Comment by isaki001** [comment]
Does it work if you do `nvcc 1.cu -arch=sm_89 -o hello`?

**Comment by f1974939505** [comment]
it works

**Comment by isaki001** [comment]
I expected 89-real to work. I would recommend trying to find the right flag. 
Could you also try passing -DTARGET_ARCH="native" in your cmake?

**Comment by f1974939505** [comment]
It still returns the same error.
  ptxas fatal : Value 'sm_30' is not defined for option 'gpu-name'

**Comment by isaki001** [comment]
I'm curious if -DTARGET_ARCH=89 would make any difference. 
I did a quick search and I have not found anything else in terms of the appropriate flag for 4090. I don't know if there are any limitations with CMake but I suspect it's just not the right flag. I would suggest searching a bit more. As a last resort we could hack things by hardcoding the arch flags on each compilation target, but I would like to avoid that. At that point you might as well not use CMake at all.

**Comment by f1974939505** [comment]
-DTARGET_ARCH=89 does not work. it still returns the same errors. btw my cmake version is 3.27.0.

**Comment by f1974939505** [comment]
It finally worked! I upgraded ubuntu from 20.04 to 24.04. It seems to be because older versions of Ubuntu don't support the latest cpus and gpus well. 

I've run the demo, and I'm not encountering any errors so far. But I'm sorry I'm not very familiar with cuda programming and can't quite see how to call pagani to compute a given integrand. Can you provide a guide on how to call the pagani function? Thank you very much!

**Comment by isaki001** [comment]
@f1974939505 That's great news! 

To run PAGANI, you have to instantiate an object of the Workspace class (`https://github.com/marcpaterno/gpuintegration/blob/master/cuda/pagani/quad/GPUquad/Workspace.cuh`). 
You can see an example of how that is done in `https://github.com/marcpaterno/gpuintegration/blob/master/cuda/pagani/demos/gaussians.cu`. 
Also, the good thing about PAGANI is you don't need to know much CUDA at all, just create a class like the ones in `"common/cuda/integrands.cuh`, and make sure to have the `__device__` placed like in the examples. 
Then instantiate your integrand and pass it as an argument to the `Workspace::integrate` routine. 

There is a lot of extra stuff in those demos, but you just need to instantiate Workspace, and have a `constexpr ndim` variable that matches the number of variables in your integrand, 
The Worksace::integrate function returns an object of type `integration_result` see (`https://github.com/marcpaterno/gpuintegration/blob/master/common/integration_result.hh`). 
The integration result is in `integration_result.estimate` and the error estimate in `integration_result.errorest`

Can you give it a shot by trying to follow the above steps and do it like it occurs in the demo https://github.com/marcpaterno/gpuintegration/blob/master/cuda/pagani/demos/gaussians.cu?

**Comment by f1974939505** [comment]
@isaki001 I've been able to compute custom integrands. Thanks again for your guidance! btw, I've noticed peak_loc in the integrand class definition, may I ask if pagani is able to compute its own optimization based on the peak position of a given function?

**Comment by isaki001** [comment]
@f1974939505 Happy to help! 

The `peak_loc` variable is not used by PAGANI, it was only for a particular integrand where I wanted to use different peak locations for testing. 

PAGANI doesn't have any functionality centered around the user providing peak locations so there are no such optimizations. 

However, you can call `integrate` with your own sub-division of the integration (checkout the `Sub_regions` type for how to define it, it's essentially about providing upper and lower bounds on each dimensional axis). 
So if you know where the peaks are, you can potentially generate more intelligent sub-divisions that PAGANI will benefit from since it would save some iterations. If you know the peak, you could also input a more restrictive integration volume around that peak instead of integration from 0 to 1 on each dimension. That way PAGANI will not have to use any iterations to find the peak.

**Comment by f1974939505** [comment]
Could you explain integration_result.status? I've noticed its output value maybe 0 or 1.

**Comment by isaki001** [comment]
Hi @f1974939505 

A status of `1` means that the integration algorithm has converged to a sufficiently accurate error estimate given the user's provided relative and absolute error tolerances (`epsrel` and `epsabs` are arguments to integrate routine). More precisely, it means that the ratio `errorest /estimate` is smaller than `epsrel` or that the `error-estimate` is smaller than `epsabs`.  When the status is `0`, that criteria has not been met and it means that the integration error and by extension the results, are not as trustworthy as the user wants. In that case, you try experimenting with different parameters to see if you can get a status of `1`, or you may need to use another algorithm (we have m-Cubes as an alternative to PAGANI).

**Comment by marcpaterno** [comment]
Hi @f1974939505 . The `status` member of the `integration_results` struct is a flag that indicates whether the algorithm has converged or not, as Ioannis described above.

However, he had a typo in his reponse. `status=0` indicates that the algorithm has converged, and `status=1` indicates the algorithm has not converged.

I'm going to close this issue as it seems that your initial question was answered. Please do not hesitate to open a new issue if you run into different problems.
