### ISSUE TITLE
How to do a 1-d integration with pagani or m-cube?

### ISSUE THREAD

**Issue by f1974939505** [marcpaterno/gpuintegration#5]

**Comment by marcpaterno** [comment]
PAGANI can not be used for 1-d integration; the set of rules it applies work only in two or more dimensions.

m-cubes should require no special handling for 1-d integrals. m-cubes is a Monte Carlo algorithm, and so It is not likely to be especially efficient for 1-d integrals.

**Comment by f1974939505** [comment]
How should I compile this project into a library and put it into my other programs that need calculations? I can now write the interface to call pagani but don't know much about cmake or how to compile such an awesome project into a library.

**Comment by f1974939505** [comment]
What is the meaning of the boolean variable "use_custom" in the template of gauss_time_and_call?
